development:
  crypt_key: "0qBqYuEa1JLlW/nDRTR2SpwY8vOhPX7S2g8S+uX87BEh/MoF9R/pKzPW9dxVOK9eWQcd1zMqpIsdeExEWrDhYg=="
test:
  crypt_key: "q0Y/M/nnMiyISNmPMjVqgmbLnUMxIcWYWTrgTL523SczLAgCWA5cL14sisIBvepy/LqBfXU66CWZGT5AH5PlBA=="
production:
  crypt_key: "o/EGxjLneznVqxI1AhIEqRjnpvS8vAetNH1Cn9o7tyx69mzKcVolMHyOFaoYrXLxRAjtKTTejjR70Z0tpa1tWQ=="
